version: "3.7"
services:
  app:
    image: 0xaliraza/wordsery
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: wordsery-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - wordsery

  db:
    image: mysql:8
    container_name: wordsery-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      # MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      #MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - db:/var/lib/mysql
    networks:
      - wordsery

  nginx:
    image: nginx:alpine
    container_name: wordsery-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - wordsery

  phpmyadmin:
      image: phpmyadmin
      container_name: phpmyadmin
      environment:
      - PMA_HOST=db
      - MYSQL_USERNAME=${DB_USERNAME}
      #- MYSQL_PASSWORD=${DB_PASSWORD}
      #- MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      restart: unless-stopped
      ports:
      - 8081:80
      networks:
      - wordsery

volumes:
  db:

networks:
  wordsery:
    driver: bridge